name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - master  # Change this if you're using a different main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'  # Ensure this matches your project target

    - name: Restore dependencies
      run: dotnet restore ./src/SimpleBlazorMultiselect.Demo/SimpleBlazorMultiselect.Demo.csproj

    - name: Build Blazor WebAssembly project
      run: dotnet publish ./src/SimpleBlazorMultiselect.Demo/SimpleBlazorMultiselect.Demo.csproj -c Release -f net8.0 -o dist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Ensure your Actions permissions allow writing
        publish_branch: gh-pages
        publish_dir: ./dist/wwwroot
