name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger workflow when pushing to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for building

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'  # Make sure this matches your target framework

    - name: Restore dependencies
      run: dotnet restore ./src/SimpleBlazorMultiselect.Demo/SimpleBlazorMultiselect.Demo.csproj

    - name: Build Blazor WebAssembly project
      run: dotnet publish ./src/SimpleBlazorMultiselect.Demo/SimpleBlazorMultiselect.Demo.csproj -c Release -f net8.0 -o dist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        # Path to the folder where your build output is located
        folder: dist
        # Set the branch where GitHub Pages will be deployed
        target-branch: gh-pages
        # Set GitHub token
        token: ${{ secrets.GITHUB_TOKEN }}
